package com.opentrace.server.services.auth.jwt;

import com.opentrace.server.models.dto.UserDTO;
import com.opentrace.server.providers.security.JwtProvider;
import com.opentrace.server.utils.parsers.RolePermissionParser;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class TokenIssuanceServiceTest {

    @Mock
    private RolePermissionParser roleParser;

    @Mock
    private JwtProvider jwtProvider;

    @InjectMocks
    private TokenIssuanceService tokenIssuanceService;

    @Test
    @DisplayName("Should parse roles and issue a token correctly")
    void shouldAuthorizeAndReturnToken() {
        UserDTO userDTO = new UserDTO();
        userDTO.setEmail("tester@example.com");
        String rawRoles = "admin, user";
        List<String> parsedRoles = List.of("ADMIN", "USER");
        String expectedToken = "header.payload.signature";

        when(roleParser.parseRoles(rawRoles)).thenReturn(parsedRoles);
        when(jwtProvider.createToken(userDTO, parsedRoles)).thenReturn(expectedToken);

        String resultToken = tokenIssuanceService.authorize(userDTO, rawRoles);

        assertEquals(expectedToken, resultToken, "The service should return the token generated by JwtProvider");

        verify(roleParser, times(1)).parseRoles(rawRoles);
        verify(jwtProvider, times(1)).createToken(userDTO, parsedRoles);
    }
}